//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.USERSPRODUCTLISTs = new HashSet<USERSPRODUCTLIST>();
        }
    
        public int PRD_ID { get; set; }
        public string PRD_NAME { get; set; }
        public string PRD_PRICE { get; set; }
        public string PRD_IMGNAME { get; set; }
        public Nullable<int> PRD_CREATEDBY { get; set; }
        public Nullable<System.DateTime> PRD_CREATEDAT { get; set; }
        public Nullable<int> PRD_UPDATEDBY { get; set; }
        public Nullable<System.DateTime> PRD_UPDATEDAT { get; set; }
    
        public virtual USERS_PROFILE USERS_PROFILE { get; set; }
        public virtual USERS_PROFILE USERS_PROFILE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERSPRODUCTLIST> USERSPRODUCTLISTs { get; set; }
    }
}
