//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSPRODUCTLIST
    {
        public int PDL_ID { get; set; }
        public Nullable<int> PDL_PRODUCTID { get; set; }
        public Nullable<int> PDL_USERID { get; set; }
        public Nullable<System.DateTime> PDL_CREATEDAT { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USERS_PROFILE USERS_PROFILE { get; set; }
    }
}
