//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_PROFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS_PROFILE()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
            this.PRODUCTS1 = new HashSet<PRODUCT>();
            this.USERSPRODUCTLISTs = new HashSet<USERSPRODUCTLIST>();
        }
    
        public int USR_ID { get; set; }
        public string USR_FNAME { get; set; }
        public string USR_LNAME { get; set; }
        public string USR_EMAILADDRESS { get; set; }
        public string USR_PASSWORD { get; set; }
        public string USR_PHONENO { get; set; }
        public Nullable<bool> USR_ISADMIN { get; set; }
        public Nullable<System.DateTime> CREATEDAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERSPRODUCTLIST> USERSPRODUCTLISTs { get; set; }
    }
}
